version: '3'

services:
  db:
    build: ./db
    ports:
      - '3316:3306'
    environment:
      MYSQL_DATABASE: 'gruz'
      MYSQL_USER: 'root1'
      MYSQL_PASSWORD: 'password1'
      MYSQL_ROOT_PASSWORD: 'password1'
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql